# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
print(np.show_config())

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda\\Library\\include']
blas

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
#print(x.size)
#print(x.itemsize)
print(x.size*x.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [10]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [14]:
y = np.arange(10,49,3)
print(y)

[10 13 16 19 22 25 28 31 34 37 40 43 46]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [53]:
a = [1,2,3,4,5]
b = [[5],
    [6],
    [7],
    [8]]
y = np.flipud(a)
print(y)


#y = a[::-1]
#print(y)

[5 4 3 2 1]
<class 'numpy.ndarray'>


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [7]:
x = np.arange(9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [8]:
a = [1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [35]:
from numpy import random
x = np.random.random((3,3,3))
print(x)

[[[0.9709401  0.79539997 0.75058918]
  [0.52648893 0.59270427 0.83527364]
  [0.792357   0.01190867 0.71262653]]

 [[0.99733355 0.27084818 0.06422677]
  [0.5314475  0.06909747 0.89775036]
  [0.40023754 0.34187837 0.64333134]]

 [[0.98461105 0.45066341 0.704684  ]
  [0.93641962 0.26761318 0.2043583 ]
  [0.01417704 0.56509871 0.82704985]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [28]:
x = np.random.random((10,10))
print(x)
print(x.min(),x.max())

[[0.21170247 0.47127921 0.07306502 0.03535305 0.92139437 0.18029025
  0.42849228 0.44837225 0.45768173 0.56122596]
 [0.14229051 0.77942542 0.76898108 0.8516312  0.22756586 0.97089969
  0.83809772 0.78737094 0.1577153  0.63695667]
 [0.51095679 0.12437059 0.53273214 0.72107515 0.28367592 0.70459047
  0.58063013 0.20846615 0.4721995  0.02053083]
 [0.29287366 0.1557198  0.22300301 0.20589247 0.13927379 0.07270466
  0.55677181 0.83069259 0.69103334 0.16066772]
 [0.17723409 0.27105986 0.9573617  0.30242425 0.9228497  0.10775107
  0.70832743 0.90684699 0.97313545 0.31121757]
 [0.41272763 0.98703455 0.35689026 0.3840062  0.98255786 0.07627652
  0.74971576 0.52499109 0.34410482 0.01731803]
 [0.25262262 0.68139441 0.8856157  0.13333808 0.48280396 0.42652824
  0.87532218 0.34793949 0.87120534 0.852092  ]
 [0.10758043 0.47244278 0.78489366 0.12407875 0.20109015 0.97073081
  0.71114568 0.80940499 0.43030308 0.95509845]
 [0.74316408 0.60412258 0.28610934 0.91508552 0.95817747 0.04235656
  0.15888753

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [36]:
x = np.random.random(30)
print(x.mean())

0.47179369401278787


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [74]:
x = np.ones((4,4))
#print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [55]:
x = np.arange(9).reshape(3,3)
y = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(y)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [83]:
x = np.diag([1, 2, 3, 4],k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [84]:
x = np.ones((8,8),dtype=int)
x[::2,::2] = 0
x[1::2,1::2] = 0
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [93]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [103]:
x = np.array([[1,0],[0,1]])
print(np.tile(x,(4,4)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [108]:
x = np.random.random((5,5))
y = (x-x.min())/(x.max() - x.min())
print(y)

[[0.09943193 0.50473966 0.54623588 0.17485764 0.44231824]
 [0.16165059 0.19913205 0.8741038  0.84689043 0.84289976]
 [0.19892512 1.         0.50159525 0.08693358 0.78627662]
 [0.3706214  0.57927311 0.23732418 0.93268703 0.62870762]
 [0.34703828 0.         0.75092086 0.35711392 0.2223225 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [112]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [116]:
x = np.dot(np.ones((5,3)),np.ones((3,2)))
print(x)

y = np.ones((5,3)) @ np.ones((3,2))
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [119]:
x = np.arange(10)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [120]:
print(sum(range(5),-1))

#numpy.sum considers -1 as axis,thats why no change has been reflected in the sum
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [134]:
Z=np.array([1])
print(Z)



[1]


array([False])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [140]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [145]:
x = np.random.uniform(-50,+50,5)
y = np.copysign(np.ceil(np.abs(x)),x)
print(x)
print(y)

#x2=np.abs(x)
#print(x2)
#x3=np.ceil(x2)
#print(x3)
#x4=np.copysign(x3,x)
#print(x4)

[ 41.93855755  37.52195872  21.35971536 -22.75266516  47.87510601]
[ 42.  38.  22. -23.  48.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [146]:
x = np.array([1,2,4,6,7])
y = np.array([2,3,8,4,7,0])
print(np.intersect1d(x,y))

[2 4 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [154]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [155]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [159]:
yest = np.datetime64("today","D") - np.timedelta64(1,"D")
today = np.datetime64("today","D")
tomorrow = np.datetime64("today","D") + np.timedelta64(1,"D")
print(yest)
print(today)
print(tomorrow)

2022-02-07
2022-02-08
2022-02-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [171]:
x = np.arange("2016-07","2016-08", dtype="datetime64[D]")
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [183]:
A = np.arange(3.0)
B = np.arange(4.0,7.0)

np.add(A,B,out = B)

np.divide(A,2,out=A)

np.negative(A,out =A)

np.multiply(A,B,out=A)

array([-0., -3., -8.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [198]:
x = np.random.uniform(0,5,5)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x)-1)
print(x.astype("int64"))
print(np.trunc(x))

[2. 4. 1. 0. 4.]
[2. 4. 1. 0. 4.]
[2. 4. 1. 0. 4.]
[2 4 1 0 4]
[2. 4. 1. 0. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [210]:
#method1
x = np.ones((5,5))
y = np.multiply(np.arange(0,5),x)

#method2
x *= np.arange(5)

print(x)
print(y)

#method3
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [211]:
def generate():
    for x in range(10):
        yield x
print(np.fromiter(generate(),int,count=-1))

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [220]:
x=np.linspace(0,1,num = 11,endpoint = False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [222]:
x = np.random.random(10)
x.sort()
print(x)

[0.04743219 0.30884768 0.38585539 0.40602417 0.47337216 0.52309355
 0.53120829 0.78406038 0.81958784 0.89383919]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [229]:
x = np.arange(1,10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [235]:
A = np.random.randint(0,10,5)
print(A)
B = np.random.randint(0,10,5)
print(B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

[3 6 7 2 2]
[5 7 0 4 7]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [236]:
x = np.zeros(10)
print(x)
x.flags.writeable = False
x[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [243]:
z = np.random.random((10,2))
#print(z)
x,y = z[:,0],z[:,1]
#print(x,y)
sq = np.sqrt(x**2 + y**2)
a= np.arctan2(y,x)
print(sq)
print(a)

[0.41336337 0.66340031 0.43242507 0.94137802 0.31666477 0.68990494
 0.72881597 0.81000922 1.07728026 0.88700757]
[0.7217828  0.35609057 0.57401111 0.04653608 1.54059803 1.53375265
 0.35894492 0.74945724 0.95591848 1.49729751]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [247]:
x = np.random.randint(1,10,10)
print(x)
x[x.argmax()] = 0
print(x)

[9 8 3 5 8 2 2 6 3 1]
[0 8 3 5 8 2 2 6 3 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [248]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,5,5), np.linspace(0,5,5))
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (1.25, 0.  ) (2.5 , 0.  ) (3.75, 0.  ) (5.  , 0.  )]
 [(0.  , 1.25) (1.25, 1.25) (2.5 , 1.25) (3.75, 1.25) (5.  , 1.25)]
 [(0.  , 2.5 ) (1.25, 2.5 ) (2.5 , 2.5 ) (3.75, 2.5 ) (5.  , 2.5 )]
 [(0.  , 3.75) (1.25, 3.75) (2.5 , 3.75) (3.75, 3.75) (5.  , 3.75)]
 [(0.  , 5.  ) (1.25, 5.  ) (2.5 , 5.  ) (3.75, 5.  ) (5.  , 5.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [249]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [250]:
#for integer types
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
#for float types
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [251]:
np.set_printoptions(threshold=np.inf)
x = np.zeros((20,20))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [252]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

76


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [253]:
z = np.ones(5, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(z)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [255]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
A = np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(A)

[[0.20784734 0.95390164]
 [0.02076623 0.50338584]
 [0.54001611 0.66051068]
 [0.10967249 0.5287809 ]
 [0.43669868 0.93036373]
 [0.28843554 0.86266411]
 [0.05545267 0.86268103]
 [0.23408739 0.63298929]
 [0.3419182  0.88583703]
 [0.62275604 0.5685982 ]]
[[0.         0.48781536 0.44318658 0.43630946 0.23005861 0.12173226
  0.17761007 0.32198335 0.15035885 0.56622254]
 [0.48781536 0.         0.54250222 0.09246205 0.59607879 0.44802649
  0.36096562 0.24960564 0.49940715 0.60551167]
 [0.44318658 0.54250222 0.         0.45005375 0.28895529 0.32273642
  0.52504722 0.30716414 0.30002458 0.12366811]
 [0.43630946 0.09246205 0.45005375 0.         0.51789468 0.37872711
  0.33827368 0.16229127 0.42594266 0.51462622]
 [0.23005861 0.59607879 0.28895529 0.51789468 0.         0.16298834
  0.38720726 0.35983731 0.10471851 0.40680664]
 [0.12173226 0.44802649 0.32273642 0.37872711 0.16298834 0.
  0.23298287 0.23601746 0.05828704 0.44524708]
 [0.17761007 0.36096562 0.52504722 0.33827368 0.38720726 0.23298287

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [256]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [260]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [264]:
x = np.arange(4).reshape(2,2)
print(x)

for ind,ele in np.ndenumerate(x):
    print(ind,ele)
    
print("\n")
    
for ind in np.ndindex(np.shape(x)):
    print(ind,x[ind])

[[0 1]
 [2 3]]
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [267]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [268]:
n = 5
p = 3
Z = np.zeros((n,n))

a = np.random.choice(range(n*n), p, replace=False)
print(a)

np.put(Z, a,5)
print(Z)

[ 5 24 10]
[[0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [269]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-3.80953487e-01  4.74881076e-01 -2.41814774e-01  4.63693232e-01
   3.67818861e-01  4.95083793e-01 -2.01852825e-01 -2.57479737e-01
  -3.69056581e-01 -3.50319560e-01]
 [ 2.76182337e-01 -6.19847584e-02 -4.84223587e-01 -4.55919589e-02
   1.74933772e-01 -2.10713387e-01  2.52632030e-01  3.27350348e-01
  -3.73732301e-01  1.45147505e-01]
 [ 2.79729565e-01 -5.89570611e-01  3.72897683e-02  8.98154916e-02
   1.80365992e-01  3.16583086e-01 -2.17036054e-01  1.57814408e-01
  -4.55661880e-01  2.00670233e-01]
 [-1.50252681e-01  1.02507077e-01  8.80116236e-02 -4.90194080e-01
  -3.96580535e-01 -3.21364460e-04  4.72410364e-01 -5.05532315e-01
   4.68331938e-01  4.11619972e-01]
 [-9.43367485e-02 -2.62462700e-01 -4.54049732e-01  3.32994967e-01
  -3.00549593e-02 -4.44249824e-01 -7.42888522e-02  2.48400782e-01
   3.38882032e-01  4.39165035e-01]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [270]:
a = np.array([[9, 2, 3],[4, 5, 8],[7, 1, 6]])
b = a[a[:,1].argsort()]
print(b)

[[7 1 6]
 [9 2 3]
 [4 5 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [271]:
x = np.random.randint(0,3,(5,10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [272]:
x = np.random.uniform(0,1,(6,6))
print(x)
y = 0.5
k = np.abs(x - y).argmin()
print(k)
z = x.flat[k]
print(z)

[[0.06689216 0.00188643 0.2718363  0.52290873 0.89430332 0.8983449 ]
 [0.86997206 0.76363877 0.75374959 0.31957032 0.32582433 0.59031859]
 [0.40244115 0.78742012 0.56840444 0.06050057 0.75505227 0.7437969 ]
 [0.95446741 0.21720706 0.46417013 0.63733628 0.77470002 0.10831859]
 [0.20644208 0.85371671 0.34074123 0.86664987 0.02378743 0.06923021]
 [0.55700579 0.17228299 0.74912948 0.45085302 0.95490704 0.5983738 ]]
3
0.5229087265509188


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [276]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)
it = np.nditer([A,B,None])
for x,y,z in it:     
    z[...] = x + y
    print(z)
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
0
1
2
1
2
3
2
3
4
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [278]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "method1")
print (Z.name)

method1


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [279]:
Z = np.ones(5)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

#np.add.at(Z, I, 1)
#print(Z)

[6. 5. 3. 7. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [280]:
#I is index,X is weights of bincount
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [281]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [282]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[57 36 56 65]
 [58 75 51 49]
 [74 39 62 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [283]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.60080779 0.49896844 0.56062503 0.37547576 0.42701681 0.57137003
 0.47290609 0.60410777 0.53394441 0.40816413]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [284]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
  
print(np.diag(np.dot(A, B)))

[0.91593701 2.32095811 0.43081343 0.90885282 1.18048679]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [286]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [288]:
A = np.ones((5,5,3))
B = 5*np.ones((5,5))
print(A * B[:,:,None])

[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [289]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,3]] = A[[3,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [290]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  7) ( 0, 43) ( 7, 43) ( 7, 45) ( 7, 56) (10, 31) (10, 57) (15, 84)
 (15, 94) (20, 74) (20, 87) (20, 89) (20, 95) (26, 67) (26, 87) (27, 73)
 (27, 98) (31, 57) (45, 56) (65, 84) (65, 95) (67, 87) (73, 98) (74, 87)
 (81, 83) (81, 84) (83, 84) (84, 94) (84, 95) (89, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [291]:
A = [1,1,2,3,4,4,6]
C = np.bincount(A)
print(C)
B = np.arange(len(C))
#print(B)
A = np.repeat(B, C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [292]:
def moving_average(a, n=3) :
    k = np.cumsum(a, dtype=float)
    k[n:] = k[n:] - k[:-n]
    return k[n - 1:] / n
Z = np.arange(20)
print(Z)
print(moving_average(Z, n=3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [293]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    #print(a.size)
    #print(shape)
    strides = (a.itemsize, a.itemsize)
    #print(a)
    #print(strides)
    return stride_tricks.as_strided(a, shape, strides)
    #return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(20), 3)
print(Z)

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [296]:
x = np.random.randint(0,2,100)
print(x)
print(np.logical_not(x, out=x))

y = np.random.uniform(-1.0,1.0,100)
print(y)
print(np.negative(y, out=y))

[0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0
 0 0 1 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 1
 1 1 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1]
[1 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 0 1 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1 1 0 1 0 0 0
 0 0 0 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0]
[-0.23955406  0.68400753  0.54656556  0.4576727   0.13168072 -0.41437108
  0.15203384  0.40629264  0.44715919 -0.02279265  0.10101437  0.93147339
  0.60250124  0.4480497   0.30720965 -0.42764608 -0.61721556  0.15778106
 -0.68999954 -0.2225855  -0.67613082 -0.55848198 -0.28776549 -0.16923442
  0.4149339   0.72794031  0.91395365  0.2634883   0.07910277 -0.08514294
  0.18508632 -0.81516508 -0.62241228 -0.65720395  0.58174768 -0.59450946
  0.37341472 -0.40448562 -0.09364462  0.80749791 -0.69358919  0.60196529
  0.25664937  0.37370184 -0.131565   -0.278885   -0.57227927 -0.61624596
 -0.7656

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [298]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[15.98940108  7.68311709  2.0440464  13.18612136  4.92701978  2.74984837
 12.92743759  0.12351771 12.82141268  4.57557378]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [299]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[6.02787970e+00 1.54106854e+00 5.25568935e+00 2.18376745e+00
  5.74572022e+00 5.92493781e+00 2.30474342e+00 8.03652778e+00
  4.51679883e-02 1.16191016e+01]
 [7.60859474e-01 7.23072419e+00 1.14693331e+00 5.61944416e+00
  5.48427914e+00 4.08037527e+00 5.36760207e+00 1.00645046e+01
  4.52743488e+00 6.77184653e+00]
 [2.01289455e+00 4.49201354e+00 6.73656736e-03 5.64107967e+00
  4.41670995e+00 3.51430750e+00 3.62052808e+00 8.33809983e+00
  2.17100069e+00 9.18829967e+00]
 [9.03823435e+00 1.25918685e-01 1.60672576e+00 1.00304597e+01
  1.85851381e+00 1.93267235e+00 3.41553842e+00 1.23525264e+00
  5.28181762e+00 1.66343977e+01]
 [2.90491101e+00 1.13199219e+01 5.47164651e+00 8.92847471e+00
  3.56937340e+00 1.43872555e+00 9.95588017e+00 9.30418409e+00
  5.20993745e+00 5.92115891e+00]
 [7.77499020e+00 1.27189198e+01 1.52075938e+00 3.14099947e+00
  1.01808270e+01 7.75587561e+00 7.42586045e+00 1.59567888e+01
  1.13163232e+01 8.00557347e-02]
 [9.81163768e+00 5.50647055e+00 7.21166239e+00 1.82636616e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [300]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[2 5 7 7 2 2 9 7 5 9]
 [2 2 8 3 2 5 0 3 8 0]
 [5 5 0 4 6 5 5 6 1 3]
 [9 0 2 1 9 8 0 4 3 2]
 [5 6 0 8 9 7 8 0 9 5]
 [8 1 2 7 2 5 0 9 7 3]
 [0 9 9 5 0 8 2 0 4 1]
 [9 0 0 3 3 6 1 5 6 6]
 [9 1 8 0 2 8 5 0 9 0]
 [8 3 9 0 2 0 3 5 4 1]]
[[0 0 0 0 0]
 [0 2 5 7 7]
 [0 2 2 8 3]
 [0 5 5 0 4]
 [0 9 0 2 1]]


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [302]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [303]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [305]:
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [315]:
Z = np.random.randint(0,5,(10,10))
print(Z)
print(Z.shape)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
print(Z.strides)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[0 0 0 3 1 3 1 4 4 2]
 [3 3 4 3 1 4 3 3 2 4]
 [4 2 0 2 1 0 0 1 4 0]
 [2 4 4 2 0 1 4 3 4 3]
 [0 2 0 2 1 2 2 1 3 4]
 [4 3 2 0 4 4 3 4 2 0]
 [4 2 4 0 1 2 4 2 3 4]
 [0 4 2 1 4 1 4 3 2 1]
 [2 1 3 2 2 3 3 3 2 0]
 [2 1 2 1 2 3 4 4 2 4]]
(10, 10)
(40, 4)
[[[[0 0 0]
   [3 3 4]
   [4 2 0]]

  [[0 0 3]
   [3 4 3]
   [2 0 2]]

  [[0 3 1]
   [4 3 1]
   [0 2 1]]

  [[3 1 3]
   [3 1 4]
   [2 1 0]]

  [[1 3 1]
   [1 4 3]
   [1 0 0]]

  [[3 1 4]
   [4 3 3]
   [0 0 1]]

  [[1 4 4]
   [3 3 2]
   [0 1 4]]

  [[4 4 2]
   [3 2 4]
   [1 4 0]]]


 [[[3 3 4]
   [4 2 0]
   [2 4 4]]

  [[3 4 3]
   [2 0 2]
   [4 4 2]]

  [[4 3 1]
   [0 2 1]
   [4 2 0]]

  [[3 1 4]
   [2 1 0]
   [2 0 1]]

  [[1 4 3]
   [1 0 0]
   [0 1 4]]

  [[4 3 3]
   [0 0 1]
   [1 4 3]]

  [[3 3 2]
   [0 1 4]
   [4 3 4]]

  [[3 2 4]
   [1 4 0]
   [3 4 3]]]


 [[[4 2 0]
   [2 4 4]
   [0 2 0]]

  [[2 0 2]
   [4 4 2]
   [2 0 2]]

  [[0 2 1]
   [4 2 0]
   [0 2 1]]

  [[2 1 0]
   [2 0 1]
   [2 1 2]]

  [[1 0 0]
   [0 1 4]
   [1 2 2]]

  [[0 0 1]
  

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [316]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 17  4 10  8]
 [17  2 13  7  8]
 [ 4 13  0 42 16]
 [10  7 42  5 10]
 [ 8  8 16 10  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [323]:
p, n = 2, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
print(M)
print(V)
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]]
[[20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [324]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [325]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [329]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)
# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9009 7579 1605 7482 3113 1459  532 7673 1346  930 8089 9781   29 5097
 6858 2146 3887  393 9264 1475 5779 3164 1104  650 2149 2671 5583 3793
 6356 9704 7810 8311 6385 2497 7078  740 1099 6636 7831 7715 2863  229
 4858 4350 1993 9442 8256 6579 5215  603 6137 9725 9978   81 1147 8466
 9963 8235 5791 5438 8148  334 9044  615  526 1412 8605 6225 1799 6253
 3984 6436 8454 6854 6171 6081 2746 8938 3991 4251 6011 9730 8751 5004
 4787 3084 2933 6742 5432 6198 4106 4546   87 8510 9137 4738 8300 9549
 9997 6656 2437 7054  580 2184 1837 8764 5808 3722 8749 2222 4772 7429
 1943 8962 7700 2423 5296 4292 2046 5679 3612 3460 4037 2980 3735 9527
 8000  239 5893  963 7399 7510 2527 6814 6561 6437 5946 6404 1807 9111
 6602 1578 5382 1250 8485 5252  104  657 2341 9753  361 1751 8346 5654
  199 9159  896 9901 7587 2472 2637 5079 4478 5321 2636 7828 1428 2246
 3609 1841 5015 4240 8262 7851 7865 7787 6120 4696 4908 7416 7452 3723
 8130  967 6331 8270 8714 7900 5372 8642 7005 9309 8034  123 8890 7866
 7175 

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [327]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [330]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [342]:
Z = np.random.randint(5e7)

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

1.22 µs ± 49.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
146 ns ± 5.78 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [343]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [344]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 3 0]
 [1 2 3]
 [3 3 4]
 [4 1 3]
 [1 1 2]
 [1 2 4]
 [3 4 1]
 [0 1 0]
 [0 1 0]
 [4 1 0]]
[[2 3 0]
 [1 2 3]
 [3 3 4]
 [4 1 3]
 [1 1 2]
 [1 2 4]
 [3 4 1]
 [0 1 0]
 [0 1 0]
 [4 1 0]]
[[2 3 0]
 [1 2 3]
 [3 3 4]
 [4 1 3]
 [1 1 2]
 [1 2 4]
 [3 4 1]
 [0 1 0]
 [0 1 0]
 [4 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [345]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [346]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [348]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A))      # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))   # np.outer(A, B)

3.7052973075346416
[0.18990941 0.37496764 0.16401373 0.12059957 0.47175293 0.08892022
 0.00721622 0.04868379 0.26272007 0.05828393]
1.7870674995153308
[[0.18990941 0.19883339 0.11936109 0.08589411 0.10938468 0.04488717
  0.01074069 0.20150755 0.09376367 0.14974492]
 [0.35813845 0.37496764 0.22509572 0.16198242 0.20628184 0.08464995
  0.0202552  0.38001068 0.17682312 0.28239471]
 [0.26095398 0.27321639 0.16401373 0.11802686 0.15030518 0.06167933
  0.01475875 0.27689095 0.12884039 0.20576406]
 [0.26664217 0.27917188 0.16758885 0.12059957 0.15358149 0.0630238
  0.01508046 0.28292653 0.13164881 0.21024924]
 [0.81903897 0.8575262  0.51477903 0.37044308 0.47175293 0.19358884
  0.04632231 0.8690593  0.40438279 0.64581804]
 [0.37620519 0.39388334 0.23645095 0.17015382 0.21668798 0.08892022
  0.021277   0.39918078 0.18574318 0.29664046]
 [0.12759219 0.13358784 0.08019372 0.05770866 0.07349099 0.03015781
  0.00721622 0.1353845  0.06299589 0.10060735]
 [0.0458817  0.04803772 0.02883738 0.02075183

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [349]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [350]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [351]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.19120377  0.18106109]
